### ISSUE TITLE
[build-error] 3dLocalEstimators.cpp related to CGAL ( MongeJetFittingMeanCurvatureEstimator.h )

### ISSUE THREAD

**Issue by phcerdan** [DGtal-team/DGtalTools#233] opened 2015-12-28 07:17 UTC
I just compiled DGtal from master with no problems with the following options:

```
ccmake -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_CXX_COMPILER_ARG1=-std=c++11 -DCMAKE_CXX_FLAGS=-std=c++11 -DWITH_QT5:BOOL=ON -DWITH_CGAL:BOOL=ON -DWITH_ITK:BOOL=ON -DWITH_EIGEN:BOOL=ON -DWITH_HDF5:BOOL=ON -DWITH_MAGICK:BOOL=ON -DWITH_OPENMP:BOOL=ON -DWITH_GMP:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/phc/devtoolset/release/DGtal -DCMAKE_BUILD_TYPE=Release ../DGtal-src
```

Facing build errors related with CGAL:

```
[24%] Building CXX object estimators/CMakeFiles/3dLocalEstimators.dir/3dLocalEstimators.cpp.o

In file included from /home/phc/Software/DGtal/DGtalTools-src/estimators/3dLocalEstimators.cpp:69:0:
/home/phc/devtoolset/release/DGtal/include/DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingMeanCurvatureEstimator.h:101:51: error: wrong number of te
mplate arguments (1, should be 3)
     typedef CGAL::Monge_via_jet_fitting<CGALKernel>  CGALMongeViaJet;
                                                   ^
In file included from /home/phc/devtoolset/release/DGtal/include/DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingMeanCurvatureEstimator.h:56:0,
                 from /home/phc/Software/DGtal/DGtalTools-src/estimators/3dLocalEstimators.cpp:69:
/usr/include/CGAL/Monge_via_jet_fitting.h:56:9: note: provided for ‘template<class DataKernel, class LocalKernel, class SvdTraits> class CGAL::Monge_via_jet_fitting’
   class Monge_via_jet_fitting {

```

**Comment by phcerdan** [comment] 2015-12-28 07:28
I obtained cgal from arch repositories, and it isn't compiled with -std=c++11 flag.
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cgal
Not sure if related.

**Comment by kerautret** [comment] 2015-12-28 08:58
Thanks @phcerdan for the issue !
Not sure that it is c++11 related but it looks like that some default template parameters of Monge_via_jet_fitting given by default with eigen3  are not given.
@JacquesOlivierLachaud we can perhaps explicitly include them in MongeJetFittingMeanCurvatureEstimator ?

**Comment by dcoeurjo** [comment] 2015-12-28 09:07
Ivthink it has nothing to do with c++11.  
For this class, the default template parameters are related to Eigen3 and Lapack. 
* what is your cgal version ?
* have you compiled cgal with eigen and lapack ?

In DGtal side, I think there is an assert and a pragma error if you try to use this functor without Eigen.

**Comment by phcerdan** [comment] 2015-12-28 15:52
I am using arch binaries for eigen (v3.2.7) and cgal (v4.7) and I have compiled atlas blas and lapack.
CGAL depends on Eigen in that binary, but neither CGAL nor Eigen depend on Lapack in arch repos.
But I couldn't find any explicit lapack dependency at compilation in CGal documentation http://doc.cgal.org/latest/Manual/installation.html#secessential3rdpartysoftware

How are the template default parameters related with the libraries? I will paste the whole error just in case.
[errorDGTAL.txt](https://github.com/DGtal-team/DGtalTools/files/73318/errorDGTAL.txt)

**Comment by dcoeurjo** [comment] 2016-05-22 11:26
hi @phcerdan , sorry for the delay.
CGAL has a "WITH_LAPACK" cmake flag to enable LAPACK dependency (CGAL4.7). The issue is clearly related to this (Mongexxx needs both Eigen and Lapack enabled in CGAL build).
Can you please retry with this flag set to ON when building CGAL ?

**Comment by phcerdan** [comment] 2016-06-06 00:32
I have asked the CGAL maintaner in Arch to add those optional flags to the build. Not really keen to install cgal from source! But I am pretty sure that's the issue, I will confirm it if those flags are changed.

**Comment by gorune** [comment] 2017-11-14 18:29
Hi, I am having similar trouble to the original post, trying the ridge detection example:
`/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:31:43: error: wrong number of template arguments (1, should be 3)
 typedef CGAL::Monge_via_jet_fitting<Kernel>    Monge_via_jet_fitting;
                                           ^
In file included from /home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:9:0:
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/../../include/CGAL/Monge_via_jet_fitting.h:59:9: note: provided for ‘template<class DataKernel, class LocalKernel, class SvdTraits> class CGAL::Monge_via_jet_fitting’
   class Monge_via_jet_fitting {
         ^
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:32:48: error: expected initializer before ‘Monge_form’
 typedef Monge_via_jet_fitting::Monge_form      Monge_form;
                                                ^
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp: In function ‘void compute_differential_quantities(PolyhedralSurf&, Poly_rings&)’:
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:134:5: error: ‘Monge_form’ was not declared in this scope
     Monge_form monge_form;
     ^
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:147:5: error: ‘monge_form’ was not declared in this scope
     monge_form = monge_fit(in_points.begin(), in_points.end(),
     ^
/home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:148:25: error: ‘monge_fit’ cannot be used as a function
       d_fitting, d_monge);
                         ^
CMakeFiles/executable.dir/build.make:62: recipe for target 'CMakeFiles/executable.dir/Compute_Ridges_Umbilics.cpp.o' failed
make[2]: *** [CMakeFiles/executable.dir/Compute_Ridges_Umbilics.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/executable.dir/all' failed
make[1]: *** [CMakeFiles/executable.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
I have (I believe) properly installed Eigen and Lapack, and reconfigured CGAL with them, I still get the above result. I am using CGAL 4.11.
Any help is appreciated, thanks.

**Comment by JacquesOlivierLachaud** [comment] 2017-11-14 19:13
Dear Gorune
I do not see any line related to DGtal in your snippet.
Do you have more context ? What are you compiling ? If this is 3dLocalEstimators.cpp, I do not see the compile line. However, I have not checked WITH_CGAL since a long time in DGtal (and I do not think that our travis CI tests this part).

**Comment by gorune** [comment] 2017-11-14 19:37
Sorry, I should have been clearer. It's only about the same error, not the DGtal:
In mine:
> /home/g/Documents/CGAL/CGAL-4.11/examples/Ridges_3/Compute_Ridges_Umbilics.cpp:31:43: error: wrong number of template arguments (1, should be 3)
typedef CGAL::Monge_via_jet_fitting Monge_via_jet_fitting;

In the original post:
> /home/phc/devtoolset/release/DGtal/include/DGtal/geometry/surfaces/estimation/estimationFunctors/MongeJetFittingMeanCurvatureEstimator.h:101:51: error: wrong number of te
mplate arguments (1, should be 3)
     typedef CGAL::Monge_via_jet_fitting<CGALKernel>  CGALMongeViaJet;

So the root of the problem is probably the same.

**Comment by dcoeurjo** [comment] 2017-11-14 21:43
The related DGtal issue had been fixed making sure that CGAL has been built using both Lapack and Eigen. Just double-check your install.
I suggest you to report the issue to https://github.com/CGAL/cgal if you still have one.

**Comment by dcoeurjo** [comment] 2017-11-14 21:45
Fixing the issue BTW (fixed in the master)

**Closed by dcoeurjo** 2017-11-14 21:45 UTC
